<a href="https://colab.research.google.com/github/BENMEZIAN/Pandas-tutorial/blob/main/Getting_started_with_Pandas%2C_reading_a_csv_file_and_Data_Frame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import pandas library

In [2]:
import pandas as pd

### Read csv file (first dataset)

In [19]:
df = pd.read_csv('sell_store_data.csv')
df

,BranchName,Week,DayWeek,Day,Month,Hour,Transaction_Type,Units,Amount
0,MyStore,1,3,2,1,9,Card,3,$54.00
1,MyStore,1,3,2,1,10,Cash,7,-$17.80
2,MyStore,1,3,2,1,10,Card,7,$41.99
3,MyStore,1,3,2,1,11,Card,20,$412.50
4,MyStore,1,3,2,1,12,Cash,1,-$18.00
...,...,...,...,...,...,...,...,...,...
4095,MyStore,53,1,31,12,13,Card,10,$129.00
4096,MyStore,53,1,31,12,14,Cash,32,-$68.36
4097,MyStore,53,1,31,12,14,Card,5,$71.00
4098,MyStore,53,1,31,12,15,Cash,66,-$359.18
4099,MyStore,53,1,31,12,15,Card,4,$130.00

### Dimension of the dataset

In [6]:
df.shape

(4100, 9)

### Display 5 first rows

In [11]:
df.head()

  BranchName  Week  DayWeek  Day  Month  Hour Transaction_Type  Units   Amount
0    MyStore     1        3    2      1     9             Card      3   $54.00
1    MyStore     1        3    2      1    10             Cash      7  -$17.80
2    MyStore     1        3    2      1    10             Card      7   $41.99
3    MyStore     1        3    2      1    11             Card     20  $412.50
4    MyStore     1        3    2      1    12             Cash      1  -$18.00

### Display last 5 rows

In [8]:
df.tail()

,BranchName,Week,DayWeek,Day,Month,Hour,Transaction_Type,Units,Amount
4095,MyStore,53,1,31,12,13,Card,10,$129.00
4096,MyStore,53,1,31,12,14,Cash,32,-$68.36
4097,MyStore,53,1,31,12,14,Card,5,$71.00
4098,MyStore,53,1,31,12,15,Cash,66,-$359.18
4099,MyStore,53,1,31,12,15,Card,4,$130.00

### Display given number of rows (for example 10)

In [12]:
df.head(10)

  BranchName  Week  DayWeek  Day  Month  Hour Transaction_Type  Units   Amount
0    MyStore     1        3    2      1     9             Card      3   $54.00
1    MyStore     1        3    2      1    10             Cash      7  -$17.80
2    MyStore     1        3    2      1    10             Card      7   $41.99
3    MyStore     1        3    2      1    11             Card     20  $412.50
4    MyStore     1        3    2      1    12             Cash      1  -$18.00
5    MyStore     1        3    2      1    12             Card      1   -$5.00
6    MyStore     1        3    2      1    12             Card     15  $118.50
7    MyStore     1        3    2      1    13             Cash     90  -$94.92
8    MyStore     1        3    2      1    13             Card     28  $423.50
9    MyStore     1        3    2      1    14             Cash     34  -$95.39

### Read csv file (second dataset)

In [22]:
df_titanic = pd.read_csv('titanic_data.csv')
df_titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,?,C,?,328,?
1305,3,0,"Zabour, Miss. Thamine",female,?,1,0,2665,14.4542,?,C,?,?,?
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.225,?,C,?,304,?
1307,3,0,"Zakarian, Mr. Ortin",male,27,0,0,2670,7.225,?,C,?,?,?
1308,3,0,"Zimmerman, Mr. Leo",male,29,0,0,315082,7.875,?,S,?,?,?

In [23]:
pd.set_option('display.max_columns', 1309)

In [24]:
df_titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,?,C,?,328,?
1305,3,0,"Zabour, Miss. Thamine",female,?,1,0,2665,14.4542,?,C,?,?,?
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.225,?,C,?,304,?
1307,3,0,"Zakarian, Mr. Ortin",male,27,0,0,2670,7.225,?,C,?,?,?
1308,3,0,"Zimmerman, Mr. Leo",male,29,0,0,315082,7.875,?,S,?,?,?